# Generated by Django 4.1 on 2022-11-13 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marcas", "0001_initial"),
        ("tipos_vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="marcas.marca"
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="tipos_vehiculos.tipovehiculo",
                    ),
                ),
            ],
        ),
    ]
