# Generated by Django 4.1 on 2022-11-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
            },
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehiculos.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
            },
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Tipo vehículo",
                "verbose_name_plural": "Tipos vehículos",
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patente", models.CharField(max_length=6)),
                ("año", models.IntegerField()),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehiculos.marca",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="vehiculos.modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
            },
        ),
        migrations.AddField(
            model_name="modelo",
            name="tipo_vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="vehiculos.tipovehiculo",
            ),
        ),
    ]
