# Generated by Django 4.1 on 2022-11-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallemantencion",
            name="vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vehiculos.vehiculo"
            ),
        ),
    ]
