# Generated by Django 4.1 on 2022-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('hash_contraseña', models.CharField(max_length=200)),
            ],
        ),
    ]
