# Generated by Django 4.1 on 2022-11-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Tipo vehículo",
                "verbose_name_plural": "Tipos vehículos",
            },
        ),
    ]
